services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    expose:
      - "5678"
    env_file:
      - .env
    volumes:
      - ./data:/home/node/.n8n
      - ./files:/files
    depends_on:
      - postgres
    networks:
      - nginx-proxy-manager_default

  postgres:
    image: postgres:15
    container_name: n8n-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true