version: '3.8'

services:
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v3
    container_name: tinyauth
    restart: always
    ports:
      - "3000:3000"
    environment:
      - SECRET=<SECRET_GENERATED>
      - APP_URL=https://<DOMAIN>
      - LOG_LEVEL=0
      - DISABLE_CONTINUE=false
      - LOGIN_MAX_RETRIES=3
      - LOGIN_TIMEOUT=300
      - USERS=<USERNAME>:$<ENCRYPTED_PASSWORD>