version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    ports:
      - "8096:8096"
    volumes:
      # Bind-mount host config, cache, media and transcode directories
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
      - ./transcode:/transcode