version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      # Bind the Docker socket so Portainer can manage your host Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Named volume "portainer_data", backed by a host bind-mount
      - portainer_data:/data

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/portainer/data